### ISSUE TITLE
issue with type varchar(max) in sql server

### ISSUE THREAD

**Issue by ldfreight** [nanodbc/nanodbc#149]
## Environment

* nanodbc version: latest
* DBMS name/version: SQL Server
* ODBC connection string: "Driver={ODBC Driver 13 for SQL Server};Server=myServer;Database=mydb;Trusted_Connection=yes;"
* OS and Compiler: Windows
* I am using nanodbc through the R package [odbc](https://github.com/r-dbi/odbc)

## Minimal Working Example
My database has a table mytable that contains a columns of type varchar(MAX):
col1 is type : int
col2 is type : varchar(max)
col3 is type : int

## Weird behavior
'SELECT col1,col**3**,col**2** FROM mytable ' => works 
'SELECT col1,col**2**,col**3** FROM mytable' => fails with error nanodbc/nanodbc.cpp:2834: 07009: [Microsoft][SQL Server Native Client 13.0]Invalid Descriptor Index

The problem is only if the varchar(max) column is not at the end. It is documented [here](https://stackoverflow.com/a/46146435/482711)

**Comment by mloskot** [comment]
AFAIU your problem, you are hitting the [known restriction in ODBC function SQLGetData](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data).
It seems you are aware of it as per the SO Q&A you linked above.

This is also explained in https://github.com/nanodbc/nanodbc/issues/8#issuecomment-336588681

I conclude it is not an issue in nanodbc. Please re-open the issue if necessary with further explanation why you think otherwise.

**Comment by Alternikaner** [comment]
#236
