### ISSUE TITLE
Can't find drivers - Conan install 

### ISSUE THREAD

**Issue by ctc-santanaa** [nanodbc/nanodbc#250]
## Environment

* nanodbc version: nanodbc/cci.20200807
* DBMS name/version: SQL Server
* ODBC connection string: driver={ODBC Driver 17 for SQL Server};server={mydb.mydomain.com,1433};database={ABC};uid=;pwd=
* OS and Compiler: Linux gcc10.1 based container. Imported using Conan from Conan center
* CMake settings: -g -ggdb3   -Wall -Wextra -Werror -std=c++2a

## Actual behavior
Throws with `[unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found`  when using the connection constructor.

## Expected  behavior
Connection is established.
I can actually connect to the db interactively using isql, so I've discarded an odbc installation issue as a possible culprit.

## Minimal Working Example
```c++
...
auto toy(std::string const & cxn_string) {
  return nanodbc::connection(cnx_string);
}

**Comment by mloskot** [comment]
This does not seem to be nanodbc issue but your ODBC driver is not configured properly. I'd suggest you to re-check the installation, https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server, web search for the error you are experiencing https://www.google.com/search?q=Can't+open+lib+'ODBC+Driver+17+for+SQL+Server'+%3A+file+not+found, check `odbcinst -j`, `cat /etc/odbcinst.ini`, `cat /etc/odbc.ini`, etc.

**Comment by ctc-santanaa** [comment]
Thanks for the reply @mloskot.
That was the first thing I checked before posting here. The driver installation and the configs in the container look good, and I can use `isql` to establish a connection and run some queries. I used the DNS field to find the connection config in the odbc.ini file, but I haven't had any luck getting that to work when starting the connection with nanodbc. 
I have also tried using the nanodbc constructor that takes the individual attributes of the connection, but I'm also getting an exception there.

**Comment by mloskot** [comment]
The nanodbc is a thin wrapper on top of the ODBC API and to establish connection it simply calls, either 
https://github.com/nanodbc/nanodbc/blob/11a827ac71016e929345699ac6297e8e64579329/nanodbc/nanodbc.cpp#L1034
or 
https://github.com/nanodbc/nanodbc/blob/11a827ac71016e929345699ac6297e8e64579329/nanodbc/nanodbc.cpp#L985

Simply, try to call either of the two functions directly, e.g. [SQLDriverConnect](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqldriverconnect-function). First, set up the environment manually, using the `connection::allocate` like it's done in the tests here
https://github.com/nanodbc/nanodbc/blob/11a827ac71016e929345699ac6297e8e64579329/test/test_case_fixture.h#L935-L940

For example:

```cpp
nanodbc::connection c;
c.allocate();
int rc  = SQLDriverConnect(c.native_dbc_handle(), 0, connection_string, SQL_NTS, nullptr, 0, nullptr, SQL_DRIVER_NOPROMPT);
```

or something similar.
If it still fails with similar error, then you get confirmation the issue is not related to the nanodbc.

**Comment by ctc-santanaa** [comment]
Forgot to close this. This is working for me now.
